### PR TITLE
fix namespace in $GLOBALS var

### PR DESCRIPTION
**Pull request by dirnbauer**
fixes missing backslashes in Documentation.

### CODE REVIEW

**Comment by s2b** [comment]
I think that if you don't use a namespace in step 5 (namespace in Fluid), you can skip the backslash. You just need to be consistent when you define it and when you use it. Or did you experience any other problems?

**Comment by dirnbauer** [comment]
hmm, in templates we use `{namespace webcon=Webcon\Theme\Components}`which might be a problem? there might be some other problems.

in our theme extension (sitepackage) we use in ext_localconf.php

```php
// Components
$GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['fluid_components']['namespaces']['\\Webcon\\Theme\\Components'] = \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extPath('theme', 'Resources/Private/Components');
```

the following code  did not work (which we "copied" from README.md)
```php
// Components
$GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['fluid_components']['namespaces']['Webcon\\Theme\\Components'] = \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extPath('theme', 'Resources/Private/Components');
```

**Comment by s2b** [comment]
Mh, that's strange. We use it like this in our projects:

```php
// Register Fluid Components
if (!isset($GLOBALS['TYPO3_CONF_VARS']['SYS']['fluid']['namespaces']['dco'])) {
    $GLOBALS['TYPO3_CONF_VARS']['SYS']['fluid']['namespaces']['dco'] = [];
}
$GLOBALS['TYPO3_CONF_VARS']['SYS']['fluid']['namespaces']['dco'][] = 'SMS\\DummyCustomerComponents\\Components';
$GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['fluid_components']['namespaces']['SMS\\DummyCustomerComponents\\Components'] =
    \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extPath(
        'dummy_customer_components',
        'Resources/Private/Components'
    );
```

As you can see we are using global namespaces. Could you check if this results in the same problem?

**Comment by s2b** [comment]
... this is especially strange because Fluid Components removes all leading and trailing backslashes:

https://github.com/sitegeist/fluid-components/blob/master/Classes/Utility/ComponentLoader.php#L203

Which version of the extension do you use?

**Comment by dirnbauer** [comment]
we removed the double backslash and it still works. 
so, no problem here. I am closing the issue.
Sorry for bothering you. :(

**Comment by s2b** [comment]
No worries, thank you for your contribution nontheless. :)

**Pull request closed without merging**
